# Generated by Django 4.2.20 on 2026-10-07 17:52

from django.db import migrations, models


def backfill_completed_carts(apps, schema_editor):
    """Preserve completed legacy purchases using their explicit fulfillment audit."""
    alias = schema_editor.connection.alias
    cart_model = apps.get_model('zeitlabs_payments', 'Cart')
    item_model = apps.get_model('zeitlabs_payments', 'CartItem')
    audit_model = apps.get_model('zeitlabs_payments', 'AuditLog')
    completed = (
        audit_model.objects.using(alias)
        .filter(action='cart_fulfilled', cart_id__isnull=False)
        .values('cart_id')
        .annotate(fulfilled_at=models.Max('created_at'))
    )
    for completion in completed.iterator():
        cart_id = completion['cart_id']
        fulfilled_at = completion['fulfilled_at']
        cart_model.objects.using(alias).filter(pk=cart_id).update(fulfilled_at=fulfilled_at)
        item_model.objects.using(alias).filter(cart_id=cart_id).update(fulfilled_at=fulfilled_at)


class Migration(migrations.Migration):

    dependencies = [
        ("zeitlabs_payments", "0002_alter_catalogueitem_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_completed_carts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                    ("payment_pending", "Payment Pending"),
                    ("refund_requested", "Refund Requested"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
